version: '3.4'
services:
  clamav:
    image: ghcr.io/t7tran/clamav:0.105.2
    read_only: true
    volumes:
    - clamav:/clamav:rw
    - tmp:/run/clamav:rw
    - tmp:/tmp:rw
  client:
    image: ghcr.io/t7tran/clamav:0.105.2
    read_only: true
    working_dir: /client
    depends_on:
    - clamav
    entrypoint:
    - sh
    command:
    - -c
    - tail -f /dev/null
    volumes:
    - ./client/clamd.conf:/etc/clamav/clamd.conf:ro
    - ./client:/client:rw
    - tmp:/tmp:rw
volumes:
  clamav:
    labels:
    - "keep=true"
    - "app=clamav"
  tmp:
    labels:
    - "app=clamav"
